name: nrk-rip
channels:
- defaults
dependencies:
- pip=9.0.1=py36_1
- python=3.6.1=2
- setuptools=27.2.0=py36_1
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py36_0
- pip:
  - certifi==2017.4.17
  - chardet==3.0.4
  - idna==2.5
  - requests==2.18.1
  - urllib3==1.21.1

